// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE


var mobile = "/mobile";

var mobileCallOrText = "/mobile/callOrText";

var mobileChatOrText = "/mobile/chatOrText";

var root = "/";

var sendSms = "/sendSms";

var chatOrText = "/chatOrText";

var loading = "/loading";

var locationSelector = "/locationSelector";

exports.root = root;
exports.sendSms = sendSms;
exports.chatOrText = chatOrText;
exports.mobile = mobile;
exports.mobileCallOrText = mobileCallOrText;
exports.mobileChatOrText = mobileChatOrText;
exports.loading = loading;
exports.locationSelector = locationSelector;
/* No side effect */
