// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var LocationItem = require("../LocationItem/LocationItem.bs.js");

var component = ReasonReact.statelessComponent("LocationsList");

function make(locations, isLoading, appendLocation, selectedLocation, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var isNoLocations = locations.length === 0;
              return React.createElement("div", undefined, isLoading ? React.createElement("div", undefined, React.createElement("div", undefined)) : null, !isLoading && !isNoLocations ? React.createElement("div", undefined, $$Array.map((function ($$location) {
                                      var actionButtonsActive = selectedLocation !== undefined ? Caml_obj.caml_equal(selectedLocation, $$location) : false;
                                      return ReasonReact.element($$location[/* id */0], undefined, LocationItem.make(appendLocation, $$location, actionButtonsActive, /* array */[]));
                                    }), locations)) : null, !isLoading && isNoLocations ? React.createElement("div", undefined, React.createElement("div", undefined, "No location matching your search, try again or enter in city, state, or zip")) : null);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
