/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as LocationsListBS from './LocationsList.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const LocationsList = ReasonReact.wrapReasonForJs(
  LocationsListBS.component,
  (function _(jsProps) {
     return Curry._5(LocationsListBS.make, jsProps.locations, jsProps.isLoading, jsProps.appendLocation, (jsProps.selectedLocation == null ? undefined : jsProps.selectedLocation), jsProps.children);
  }));

export default LocationsList;
