// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE

var Curry = require('bs-platform/lib/js/curry.js');
var React = require('react');
var ReasonReact = require('reason-react/src/ReasonReact.js');

function handleClick(appendLocation, $$location) {
  return Curry._1(appendLocation, $$location);
}

var component = ReasonReact.statelessComponent('LocationItem');

function make(appendLocation, $$location, actionButtonsActive, _children) {
  return /* record */ [
    /* debugName */ component[/* debugName */ 0],
    /* reactClassInternal */ component[/* reactClassInternal */ 1],
    /* handedOffState */ component[/* handedOffState */ 2],
    /* willReceiveProps */ component[/* willReceiveProps */ 3],
    /* didMount */ component[/* didMount */ 4],
    /* didUpdate */ component[/* didUpdate */ 5],
    /* willUnmount */ component[/* willUnmount */ 6],
    /* willUpdate */ component[/* willUpdate */ 7],
    /* shouldUpdate */ component[/* shouldUpdate */ 8],
    /* render */ function(_self) {
      var locationName = $$location[/* name */ 1];
      var match = $$location[/* address */ 2];
      return React.createElement(
        'div',
        {
          onClick: function(_e) {
            return Curry._1(appendLocation, $$location);
          }
        },
        React.createElement(
          'div',
          undefined,
          React.createElement('h1', undefined, locationName)
        ),
        match !== undefined
          ? React.createElement('div', undefined, match)
          : null
      );
    },
    /* initialState */ component[/* initialState */ 10],
    /* retainedProps */ component[/* retainedProps */ 11],
    /* reducer */ component[/* reducer */ 12],
    /* jsElementWrapped */ component[/* jsElementWrapped */ 13]
  ];
}

exports.handleClick = handleClick;
exports.component = component;
exports.make = make;
/* component Not a pure module */
